/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package accountingsystem;
import java.sql.*;
import DB.DBConnection;
import java.util.Vector;
import accountingsystem.PurchaseForm;

/**
 *
 * @author Acer
 */
public class PurchaseForm extends javax.swing.JFrame {

    /**
     * Creates new form PurchaseForm
     */
    Connection conn1=null;
    Statement stm1=null;
    ResultSet rs1=null;
    String invn1;
    Vector prodid,custid,prpr;
    void get(){
    try{
        prodid=new Vector();
        custid=new Vector();
       prpr=new Vector();
        conn1= DBConnection.getConn();
    stm1=conn1.createStatement();
    rs1=stm1.executeQuery("select invoiceNo from purchase");
    //rs1.next();
    boolean t=rs1.next();
    if(t){
      do{
      invn1=rs1.getString(1);
      String sr[]=invn1.split("_");
      int x=Integer.parseInt(sr[1]);
      x=x+1;
      invn1=sr[0]+"_"+x;
     }
     while(rs1.next()); 
    }
    
    else{
    invn1="Rathore_01";
    }
    inv1.setText(invn1);
    rs1.close();
    
    rs1=stm1.executeQuery("select pid,pname,pprice from product ");
    while(rs1.next()){
    prodid.addElement(rs1.getInt(1));
    prpr.addElement(rs1.getInt(3));
    product1.addItem(rs1.getString(2));
    }
    rs1.close();
    
    rs1=stm1.executeQuery("select cid,cname from customer where ctype=1 AND status=0");
    while(rs1.next())
    {
    custid.addElement(rs1.getInt(1));
    customer1.addItem(rs1.getString(2));
    }
    rs1.close();
    } 
    catch(Exception ee){
    System.out.println(ee);
    }
    }
    public PurchaseForm() {
        initComponents();
        get();
        setSize(500,500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        inv1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        customer1 = new javax.swing.JComboBox<>();
        product1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        puprice = new javax.swing.JTextField();
        qty = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Tamount = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        home = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Purchase Invoice Form");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(225, 30, 210, 50);

        inv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inv1ActionPerformed(evt);
            }
        });
        getContentPane().add(inv1);
        inv1.setBounds(150, 110, 110, 30);

        jLabel2.setText("inv no.1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 110, 80, 30);

        jLabel3.setText("select cust.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(330, 140, 70, 30);

        customer1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select" }));
        customer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer1ActionPerformed(evt);
            }
        });
        getContentPane().add(customer1);
        customer1.setBounds(330, 170, 110, 50);

        product1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select" }));
        product1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product1ActionPerformed(evt);
            }
        });
        getContentPane().add(product1);
        product1.setBounds(160, 160, 120, 30);

        jLabel4.setText("select product");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 160, 80, 20);

        jLabel5.setText("purchase price");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 230, 90, 16);
        getContentPane().add(puprice);
        puprice.setBounds(160, 230, 110, 30);

        qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyActionPerformed(evt);
            }
        });
        getContentPane().add(qty);
        qty.setBounds(160, 290, 110, 30);

        jLabel6.setText("qty");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(90, 290, 17, 16);
        getContentPane().add(Tamount);
        Tamount.setBounds(330, 310, 100, 50);

        jLabel7.setText("total amount");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(330, 290, 69, 16);

        save.setText("save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(140, 410, 72, 23);

        home.setText("home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home);
        home.setBounds(330, 410, 72, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyActionPerformed
        // TODO add your handling code here:
       int x= Integer.parseInt(puprice.getText());
        int y= Integer.parseInt(qty.getText());
        Tamount.setText((x*y)+"");
    }//GEN-LAST:event_qtyActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MasterPage.main(new String[2]);
    }//GEN-LAST:event_homeActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        try{
        String invoiceno=inv1.getText();
        int prodid11=(Integer)prodid.get(product1.getSelectedIndex()-1);
        int custid11=(Integer)custid.get(customer1.getSelectedIndex()-1);
        int prprice1=Integer.parseInt(puprice.getText());
        int qty11=Integer.parseInt(qty.getText());
        int total11=Integer.parseInt(Tamount.getText());
        PreparedStatement ps1=conn1.prepareStatement("insert into purchase(invoiceNo.,cid,pid,purprice,quantity,amount) values(?,?,?,?,?,?)");
        ps1.setString(1,invoiceno);
        ps1.setInt(2,custid11);
        ps1.setInt(3,prodid11);
        ps1.setInt(4,prprice1);
        ps1.setInt(5,qty11);
        ps1.setInt(6,total11);
        ps1.executeUpdate();
        puprice.setText("");
         qty.setText("");
         Tamount.setText("");
         //get();
        
    }//GEN-LAST:event_saveActionPerformed
       catch(Exception e){
    System.out.println(e);
     }   
    }
   
    private void product1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product1ActionPerformed
      
        int t= product1.getSelectedIndex();
        puprice.setText(""+prpr.get(t-1));
    }//GEN-LAST:event_product1ActionPerformed

    private void inv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inv1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inv1ActionPerformed

    private void customer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customer1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PurchaseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PurchaseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PurchaseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PurchaseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PurchaseForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Tamount;
    private javax.swing.JComboBox<String> customer1;
    private javax.swing.JButton home;
    private javax.swing.JTextField inv1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<String> product1;
    private javax.swing.JTextField puprice;
    private javax.swing.JTextField qty;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
